### ISSUE TITLE
[Feature] : A gallery carousel on homepage with heading Gallery.

### ISSUE THREAD

**Issue by SudhansuuRanjan** [SudhansuuRanjan/tesla-nitp-web#46]
**Issue Description:**
Add a new responsive gallery carousel with animations on homepage between `Message from PI` & `FAQ` component with a button that should redirect to the gallery page, and the design should be exact similar to the provided. You should not use any global styling and try not to use a heavyweight package for it. Also you need to use Tailwind CSS for styling.

For any clarification you can contact me.

**Proposed UI**

![Screenshot (1472)](https://github.com/SudhansuuRanjan/tesla-nitp-web/assets/77230416/10ac33c2-98e6-4d64-872c-8c3c5ad92803)

**Comment by tsongtheng** [comment]
@SudhansuuRanjan , assign me.

**Comment by SudhansuuRanjan** [comment]
Go for it.

**Comment by tsongtheng** [comment]
Hi @SudhansuuRanjan , should i worry about this errors?

![tesla](https://github.com/SudhansuuRanjan/tesla-nitp-web/assets/69814398/677cafd6-eda0-448c-9960-c0189fff0ecf)

**Comment by SudhansuuRanjan** [comment]
You could Ignore it since appwrite will require you to setup database schema/auth/roles and cors etc.

**Comment by tsongtheng** [comment]
Ok

**Comment by tsongtheng** [comment]
hey @SudhansuuRanjan , is this fine?


![tesla](https://github.com/SudhansuuRanjan/tesla-nitp-web/assets/69814398/3956371d-40ee-4ddc-ab56-5b0bff2701a1)

**Comment by tsongtheng** [comment]
I have used [**swiper**](https://swiperjs.com/) package in the above carousel. With packages, it is very difficult to customize only with tailwind css. I have tried since day one to customize as given in the **issue description** . Their documentation are  also not brief. I have used little bit of global style here. Will this work?


![code](https://github.com/SudhansuuRanjan/tesla-nitp-web/assets/69814398/d2261877-d2cd-4e86-91ed-9222b8fcdde4)

**Comment by SudhansuuRanjan** [comment]
Seems fine!

**Comment by SudhansuuRanjan** [comment]
Closing this issue as this is completed for now.
